In [4]:
#Import Libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from imblearn.over_sampling import SMOTE

In [10]:
#Load Your Dataset
import pandas as pd
#load data.csv fille
df1 = pd.read_csv('C:/Users/SAKTHIVEL P/Downloads/cover_type (1).csv')
df1.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type,Wilderness_Area,Soil_Type
0,2596,51,3,258,0,510,221,232,148,6279,Aspen,1,29
1,2590,56,2,212,-6,390,220,235,151,6225,Aspen,1,29
2,2804,139,9,268,65,3180,234,238,135,6121,Lodgepole Pine,1,12
3,2785,155,18,242,118,3090,238,238,122,6211,Lodgepole Pine,1,30
4,2595,45,2,153,-1,391,220,234,150,6172,Aspen,1,29


In [47]:
#Encode BEFORE split
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df1['Cover_Type'] = le.fit_transform(df1['Cover_Type'])

In [48]:
#Then split
X = df1.drop('Cover_Type', axis=1)
y = df1['Cover_Type']

In [49]:
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [50]:
#Apply SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE()

X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

In [51]:
#Train Model
rf = RandomForestClassifier()
rf.fit(X_train_res, y_train_res)

rf_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, rf_pred))

Accuracy: 0.9594557543354583


In [52]:
#Train Models
#Random Forest
rf = RandomForestClassifier()
rf.fit(X_train_res, y_train_res)

rf_pred = rf.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, rf_pred)
print(f"Random Forest Accuracy: {accuracy * 100:.2f}%")

Random Forest Accuracy: 96.02%


In [53]:
#Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train_res, y_train_res)

dt_pred = dt.predict(X_test)

In [54]:
#Logistic Regression
from sklearn.preprocessing import StandardScaler

# Create scaler
scaler = StandardScaler()

# Scale data
X_train_res_scaled = scaler.fit_transform(X_train_res)
X_test_scaled = scaler.transform(X_test)

# Train model
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_res_scaled, y_train_res)

# Predict
lr_pred = lr.predict(X_test_scaled)

In [24]:
#Logistic Regression ..."Output"...
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix 
#1. calculate & print Accuracy
lr_accuracy = accuracy_score(y_test, lr_pred)
print(f"Logistic Regression Accuracy: {lr_accuracy * 100:.2f}%")

#2. print classification Report (precision,recall , F1-score
print("\nClassification Report:")
print(classification_report(y_test, lr_pred))
#3. print confusion matrix 
print("Confusion Matrix:")
print(confusion_matrix(y_test, lr_pred))

Logistic Regression Accuracy: 66.49%

Classification Report:
                   precision    recall  f1-score   support

            Aspen       0.13      0.69      0.21       580
Cottonwood/Willow       0.77      0.85      0.81       423
      Douglas-fir       0.58      0.64      0.61       440
        Krummholz       0.62      0.96      0.75       405
   Lodgepole Pine       0.87      0.67      0.76     20709
   Ponderosa Pine       0.59      0.52      0.56       402
       Spruce/Fir       0.48      0.63      0.54      6219

         accuracy                           0.66     29178
        macro avg       0.58      0.71      0.61     29178
     weighted avg       0.76      0.66      0.70     29178

Confusion Matrix:
[[  401     0    24     0   131    12    12]
 [    0   359    26     0     0    38     0]
 [   14    58   280     0     0    88     0]
 [    0     0     0   388     0     0    17]
 [ 2536     0    24    33 13851     7  4258]
 [   18    48   125     0     0   211     0]

In [55]:
 #KNN
knn = KNeighborsClassifier()
knn.fit(X_train_res_scaled, y_train_res)

knn_pred = knn.predict(X_test_scaled)

In [27]:
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [56]:
#Train XGBoost
xgb = XGBClassifier()
xgb.fit(X_train_res, y_train_res)

xgb_pred = xgb.predict(X_test)

In [57]:
#Evaluate
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, xgb_pred))
print(classification_report(y_test, xgb_pred))

Accuracy: 0.9195626842141339
              precision    recall  f1-score   support

           0       0.74      0.93      0.82       580
           1       0.96      0.96      0.96       423
           2       0.86      0.88      0.87       440
           3       0.88      0.98      0.93       405
           4       0.97      0.93      0.95     20709
           5       0.82      0.87      0.84       402
           6       0.81      0.88      0.85      6219

    accuracy                           0.92     29178
   macro avg       0.86      0.92      0.89     29178
weighted avg       0.92      0.92      0.92     29178



In [59]:
#Evaluation Function
def evaluate_model(y_test, y_pred, model_name):
    print(f"--- {model_name} ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("\n")

In [60]:
#Evaluate All Models
evaluate_model(y_test, rf_pred, "Random Forest")
evaluate_model(y_test, dt_pred, "Decision Tree")
evaluate_model(y_test, lr_pred, "Logistic Regression")
evaluate_model(y_test, knn_pred, "KNN")
evaluate_model(y_test, xgb_pred, "XGBoost")

--- Random Forest ---
Accuracy: 0.9612379189800535
Confusion Matrix:
 [[  529     0     4     0    36     8     3]
 [    0   409     2     0     0    12     0]
 [    2     6   378     0     1    53     0]
 [    0     0     0   399     0     0     6]
 [   62     0    10     5 20156    12   464]
 [    7    11    21     0     0   363     0]
 [   12     0     2    35   357     0  5813]]
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.91      0.89       580
           1       0.96      0.97      0.96       423
           2       0.91      0.86      0.88       440
           3       0.91      0.99      0.95       405
           4       0.98      0.97      0.98     20709
           5       0.81      0.90      0.85       402
           6       0.92      0.93      0.93      6219

    accuracy                           0.96     29178
   macro avg       0.91      0.93      0.92     29178
weighted avg       0.96      0.96      0.96     

In [61]:
model_results = pd.DataFrame({
    'Model': ['Random Forest', 'Decision Tree', 'Logistic Regression', 'KNN', 'XGBoost'],
    'Accuracy': [0.9612, 0.9407, 0.6631, 0.8991, 0.9196]
})

print(model_results.sort_values(by='Accuracy', ascending=False))

                 Model  Accuracy
0        Random Forest    0.9612
1        Decision Tree    0.9407
4              XGBoost    0.9196
3                  KNN    0.8991
2  Logistic Regression    0.6631


#### 

In [62]:
# Hyperparameter Tuning
#GridSearchCV
#Import
from sklearn.model_selection import GridSearchCV

#Define Parameters
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

#Apply GridSearch
rf = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train_res, y_train_res)

#Best Parameters
print("Best Parameters:", grid_search.best_params_)
#Best Model
best_rf = grid_search.best_estimator_
#Evaluate Tuned Model
y_pred_tuned = best_rf.predict(X_test)

print("Tuned Accuracy:", accuracy_score(y_test, y_pred_tuned))
print(classification_report(y_test, y_pred_tuned))



Fitting 3 folds for each of 24 candidates, totalling 72 fits
Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Tuned Accuracy: 0.960895195009939
              precision    recall  f1-score   support

           0       0.87      0.91      0.89       580
           1       0.96      0.96      0.96       423
           2       0.90      0.86      0.88       440
           3       0.91      0.98      0.94       405
           4       0.98      0.97      0.98     20709
           5       0.80      0.89      0.84       402
           6       0.92      0.94      0.93      6219

    accuracy                           0.96     29178
   macro avg       0.90      0.93      0.92     29178
weighted avg       0.96      0.96      0.96     29178



In [80]:
print("Best Parameters:", grid_search.best_params_)
{
 'max_depth': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 200
}

Best Parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}


{'max_depth': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 200}

In [81]:
best_rf

,n_estimators,200
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [82]:
import joblib
import os

# Create folder
os.makedirs('C:/Users/SAKTHIVEL P/OneDrive/Desktop/EcoType Project/models', exist_ok=True)

# Save model
joblib.dump(best_rf, 'C:/Users/SAKTHIVEL P/OneDrive/Desktop/EcoType Project/models/final_model.pkl')

['C:/Users/SAKTHIVEL P/OneDrive/Desktop/EcoType Project/models/final_model.pkl']

In [83]:
joblib.dump(le, 'C:/Users/SAKTHIVEL P/OneDrive/Desktop/EcoType Project/models/label_encoder.pkl')

['C:/Users/SAKTHIVEL P/OneDrive/Desktop/EcoType Project/models/label_encoder.pkl']

In [ ]:
#FINAL REPORT
Final Model Selection
Random Forest was selected as the final model based on highest accuracy (~96%).
Hyperparameter tuning using GridSearchCV confirmed optimal parameters.
The model demonstrated strong performance across all classes.